### ISSUE TITLE
Problem with get_object_vars and ArrayObject

### ISSUE THREAD

**Issue by diego-sorribas** [laminas-api-tools/api-tools-hal#24]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.6.0

#### Summary
I upgraded from php5.6 to php7.4 and I found that when I use an Entity with ArrayObject and Hal want to extract it with get_object_vars I get an empty array.

[Php reference](https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.spl)
[Same Problem in zend-framework in another package](https://github.com/zendframework/zend-view/issues/202)

#### Current behavior

get_object_vars returns empty array when using on an ArrayObject

#### Expected behavior

Return an array with ArrayObject properties and values.

The solution could be add?
```
if ($entity instanceof ArrayObject) {
       return  $entity->getArrayCopy()
}
```

**Comment by weierophinney** [comment]
Fixed with #29 and released with 1.6.1.
